### ISSUE TITLE
TypeError: 'a+' not callable

### ISSUE THREAD

**Issue by yoshimo** [ngo/win-frida-scripts#3]
I am currently trying to look at traffic but when frida tries to log calls to Windows 10 lsass.exe
the logfile has besides the master screts these lines repeating all over :

```
TypeError: 'a+' not callable
    at [anon] (C:\Users\frida\Buildbot\frida-windows\build\frida-gum\bindings\gumjs\duktape.c:66061)
    at /keylog.js:4
    at /keylog.js:135
Got client random from SslGenerateMasterKey's pParameterList: 
```
What is happening here?

**Comment by ngo** [comment]
Hi! Thanks for testing out the scripts! To be honest, I have no idea what would cause such an error message - the only occurrence of "a+" would be indeed on line 4 in the File constructor, and it seems that duktape (frida's embedded js engine) is unhappy with how I call that costructor.

**Comment by ngo** [comment]
I've just retested the script on newer win and frida and cannot reproduce. Please try updating frida.
