### ISSUE TITLE
Can't attach to lsass.exe

### ISSUE THREAD

**Issue by dougbenham** [ngo/win-frida-scripts#4]
Attempting to run `frida --no-pause lsass.exe -l keylog.js`.

- Tried running as user, administrator and also as system (via psexec).
- Verified with Process Explorer that lsass.exe process does not have any `PsProtectedSigner*` flags.
- No `HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Lsa\RunAsPPL` registry flag is set.
- Tried with 32 and 64 bit python. 
- Using Frida 15.2.2 and Frida Tools 11.0.0.
- Tried with `Windows 10 2004` and `Windows 10 21H1`.

Receiving the following error message:
`Failed to attach: unexpected error writing to memory in target process (WriteProcessMemory returned 0x00000005)`

Any ideas?

**Comment by ngo** [comment]
Are you able to e.g. make a dump of lsass.exe memory using task manager? 
Is this a bare-metal install  or a VM?
Can you attach frida to another process (e.g. frida-trace explorer.exe)?

I can repro a similar error when trying to connect to lsaiso.exe process (which is protected by credential guard) - I receive a `Failed to attach: unexpected error writing to memory in target process (WriteProcessMemory returned 0x000003e6)` error.

So this is almost certainly some windows security feature preventing access to lsass.exe memory.

**Comment by ngo** [comment]
0x00000005 is usually an "access denied" error.

**Comment by dougbenham** [comment]
>Are you able to e.g. make a dump of lsass.exe memory using task manager?

No

>Is this a bare-metal install or a VM?

Bare-metal

>Can you attach frida to another process (e.g. frida-trace explorer.exe)?

Yes `frida-trace explorer.exe` runs with no problem.

**Comment by ngo** [comment]
As a last-ditch effort you could try temporarily disabling VBS by disabling core isolation in Device Security and rebooting.

But generally speaking, the fact that you cannot memory dump lsass from task manager (even running it as admin) probably means that frida also won't  be able to access this process.

**Comment by dougbenham** [comment]
It seems core isolation has never been on for me due to incompatible drivers:
![image](https://user-images.githubusercontent.com/5466350/189710468-9eae23a8-a68f-49c4-8db9-4131db2bd2f4.png)

Dang I really wish I knew what was preventing me access. I might have to reformat and start fresh I suppose.

**Comment by dougbenham** [comment]
Right before throwing in the towel and reinstalling Windows I decided to look into Avast some more. I have been running my tests with Avast shields fully disabled but figured there might be something more.. Turns out they have LSA protection that runs even when you turn off all the "protection shields":
![image](https://user-images.githubusercontent.com/5466350/189756057-9a05b74d-c30e-4342-8e97-827981e43aae.png)

Disabling this finally allows me to attach to lsass.exe!
Might be worth adding to the script instructions, I spent way too much time on this :D

**Comment by ngo** [comment]
Happy to hear that the problem is finally resolved!
I've added an AV note to README.

**Comment by AloisKraus** [comment]
@dougbenham: It would be interesting to get an ETW trace of that with 
wpr -start CPU 
attach
wpr -stop c:\temp\AvastAttachInterference.etl 
to see where AV is intercepting calls. I could add this to the known AV stacktags which shows known interference (mostly performance) with ETWAnalyzer. I am collecting such issues.

**Comment by dougbenham** [comment]
> @dougbenham: It would be interesting to get an ETW trace of that with wpr -start CPU attach wpr -stop c:\temp\AvastAttachInterference.etl to see where AV is intercepting calls. I could add this to the known AV stacktags which shows known interference (mostly performance) with ETWAnalyzer. I am collecting such issues.

I tried but keep getting this error:
```
        Cannot change thread mode after it is set.
        Profile Id: RunningProfile
        Error code: 0x80010106
```

After reviewing https://devblogs.microsoft.com/performance-diagnostics/wpr-start-and-stop-commands/ I see:
```
If wpr -stop command fails with Error code: 0x80010106
Please use the insider version of ADK Windows Performance Toolkit, build 19650 or later
```
Sadly I don't have Insider access. Tried installing latest ADK and still get the same result.

**Comment by AloisKraus** [comment]
When you use the ADK you need to prefix the wpr. Otherwise the one in your path from C:\Windows\System32 is used. 
Type `where wpr` and fully qualify the path to the wpr start/stop commands. Then it will work. I really question Quality control in that regard that essential tools are not working on a supported LTS release of Windows.

**Comment by dougbenham** [comment]
Thanks. That works. Here's the trace, let me know what you find.
[AvastAttachInterference.zip](https://github.com/ngo/win-frida-scripts/files/9564035/AvastAttachInterference.zip)

**Comment by AloisKraus** [comment]
Thanks! The data looks good. I am adding now proper stacktags for the drivers so it is easier to see Avast interfering with your process. 
After data extraction

`Etwanalyzer -extract all -fd AvastAttachInterference.etl -symserver ms`

you can query the created json file with 

`EtwAnalyzer -dump cpu -stacktags *virus* -pn Frida;python;system;lsass`

![image](https://user-images.githubusercontent.com/101576413/190118559-7e275eeb-c5d9-4bc0-a1c4-2795647144d2.png)


With 
`EtwAnalyzer -dump cpu -methods *.sys;*.dll -smi -pn Frida;python;system;lsass`

![image](https://user-images.githubusercontent.com/101576413/190128482-76aeeca5-11c7-48d9-86fa-ac768e4552cd.png)

you can see also which bad things were loaded inside your process.

**Comment by ngo** [comment]
@AloisKraus excellent addition thanks!
